# Generated by Django 2.1.4 on 2019-01-23 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birds',
            name='bird_class',
        ),
        migrations.AddField(
            model_name='birds',
            name='bird_class',
            field=models.CharField(default=datetime.datetime(2019, 1, 23, 21, 2, 54, 957158, tzinfo=utc), max_length=70),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='birds',
            name='distribution_in_bengal',
        ),
        migrations.AddField(
            model_name='birds',
            name='distribution_in_bengal',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='birds',
            name='family',
        ),
        migrations.AddField(
            model_name='birds',
            name='family',
            field=models.CharField(default=datetime.datetime(2019, 1, 23, 21, 3, 13, 877317, tzinfo=utc), max_length=70),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='birds',
            name='family_author',
        ),
        migrations.AddField(
            model_name='birds',
            name='family_author',
            field=models.CharField(default=datetime.datetime(2019, 1, 23, 21, 3, 24, 197174, tzinfo=utc), max_length=70),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='birds',
            name='genus',
        ),
        migrations.AddField(
            model_name='birds',
            name='genus',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='birds',
            name='genus_author',
        ),
        migrations.AddField(
            model_name='birds',
            name='genus_author',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='birds',
            name='order',
        ),
        migrations.AddField(
            model_name='birds',
            name='order',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='birds',
            name='phylum',
        ),
        migrations.AddField(
            model_name='birds',
            name='phylum',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birds',
            name='status',
            field=models.CharField(max_length=70),
        ),
    ]
