# Generated by Django 2.1.4 on 2019-01-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0003_auto_20190123_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birds',
            name='size_cm',
            field=models.FloatField(),
        ),
    ]
