# Generated by Django 2.1.4 on 2019-01-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0004_auto_20190123_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birds',
            name='year',
            field=models.IntegerField(),
        ),
    ]
