# Generated by Django 2.1.4 on 2019-01-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0005_auto_20190123_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birds',
            name='size_cm',
            field=models.CharField(max_length=10),
        ),
    ]
